linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - gofmt
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - maintidx
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - typecheck
    - unconvert
    - unused
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  cyclop:
    skip-tests: true
  decorder:
    dec-order:
      - type
      - var
      - const
      - func
    disable-dec-order-check: false
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
      - (io.ReadCloser).Close
      - (*database/sql.Rows).Close
      - (*encoding/csv.Writer).Write
  errchkjson:
    check-error-free-encoding: true
    report-no-exported: true
  exhaustive:
    default-signifies-exhaustive: true
  godot:
    scope: all
  mnd:
    ignored-functions:
      - 'strconv.Parse*'
      - 'strconv.Format*'
      - 'big.Parse*'
  govet:
    enable-all: true
    disable:
      - fieldalignment
  importas:
    no-extra-aliases: true
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - ^([A-Z])$
  lll:
    line-length: 120
    tab-width: 4
  misspell:
    locale: UK
    ignore-words:
      - davisd
      - color
  nakedret:
    max-func-lines: 0
  nestif:
    min-complexity: 4
  nolintlint:
    require-explanation: true
    require-specific: true
  stylecheck:
    checks:
      - all
    http-status-code-whitelist: []
  tenv:
    all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - decorder
        - dupl
        - errcheck
        - errchkjson
        - forcetypeassert
        - funlen
        - gosec
        - gocognit
        - goconst
        - godot
        - goerr113
        - maintidx
        - nilnil
        - wsl
        - lll
    - path: config/
      linters:
        - gochecknoglobals
        - gomnd
        - tagliatelle
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
